package com.example.weather.helpers

object Consts {
    val DAILY_DELEMETER:String=","
    val HOURLY_DELEMETER:String="#"
    val OBJECT_DELEMETER:String="&"
    val DIRECTORY:String="imgDir"
    val DELIMITER_IMAGE_PATH="-"
    val IMAGE_URL:String="https://openweathermap.org/img/wn/"
    val WIND_SETTINGS_KEY:String="WIND"
    val WIND_MS:String="m/s"
    val WIND_MH:String="m/h"
    val TEMP_SETTINGS_KEY:String="TEMP"
    val TEMP_C:String="CEL"
    val TEMP_K:String="KELV"
    val TEMP_F:String="FEH"
    val LANG_KEY:String="LANG"
    val LANG_EN:String="EN"
    val LANG_AR:String="AR"
    val LOCATION_KEY:String="LOCATION"
    val LOCATION_GPS:String="GPS"
    val LOCATION_MAP:String="MAP"
    val NOT_KEY:String="NOT"
    val NOT_ON:String="ON"
    val NOT_OFF:String="OFF"
    val NOT_TYPE_KEY:String="NOT_TYPE"
    val NOT_TYPE_NOTI:String="NOTI"
    val NOT_TYPE_ALARM:String="ALARM"
    val DIRECTION_FAV="DIRECTION_FAV"
    val DIRECTION_SET="DIRECTION_SET"
    val FROM_MAP_TO_FAV="honey I'm fav"
    val FROM_MAP_TO_TEST="honey I'm home"
    val API_KEY="af7545a5decb1cf13fb3c5e0a6307a3a"
    val WETDESC="WETDESC"

}